In [2]:
import numpy as np
from scipy.linalg import qr

# Example matrix A and vector b
A = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([7, 8, 9])

# QR decomposition
Q, R = qr(A)

# Least squares solution
x_ls = np.linalg.lstsq(A, b, rcond=None)[0]

print("Matrix A:")
print(A)
print("\nVector b:")
print(b)
print("\nMatrix Q:")
print(Q)
print("\nMatrix R:")
print(R)
print("\nLeast squares solution x:")
print(x_ls)

Matrix A:
[[1 2]
 [3 4]
 [5 6]]

Vector b:
[7 8 9]

Matrix Q:
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]

Matrix R:
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]

Least squares solution x:
[-6.   6.5]


In [21]:
import numpy as np
from scipy.linalg import qr

# More complicated matrix A and vector b
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10], [10, 11, 13]])
b = np.array([14, 32, 50, 68])

# QR decomposition
Q, R = qr(A)

# Least squares solution
x_ls = np.linalg.lstsq(A, b, rcond=None)[0]

print("Matrix A:")
print(A)
print("\nVector b:")
print(b)
print("\nMatrix Q:")
print(Q)
print("\nMatrix R:")
print(R)
print("\nLeast squares solution x:")
print(x_ls)

y = Q.T @ b
x_ground_truth = np.linalg.solve(R[:3, :3], y[:3])
print("\nTransformed vector y:")
print(y)
print("\nGround truth solution x:")
print(x_ground_truth)

Matrix A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]
 [10 11 13]]

Vector b:
[14 32 50 68]

Matrix Q:
[[-0.07761505 -0.83305216 -0.2236068  -0.5       ]
 [-0.31046021 -0.45123659  0.67082039  0.5       ]
 [-0.54330537 -0.06942101 -0.67082039  0.5       ]
 [-0.77615053  0.31239456  0.2236068  -0.5       ]]

Matrix R:
[[-12.88409873 -14.59162988 -17.61861693]
 [  0.          -1.0413152   -1.83965686]
 [  0.           0.          -0.4472136 ]
 [  0.           0.           0.        ]]

Least squares solution x:
[-2.00000000e+00  8.00000000e+00 -1.72919885e-14]

Transformed vector y:
[-9.09648416e+01 -8.33052161e+00  7.10542736e-15  3.55271368e-15]

Ground truth solution x:
[-2.00000000e+00  8.00000000e+00 -1.58882186e-14]


In [22]:

y = Q.T @ b
x_ground_truth = np.linalg.solve(R[:3, :3], y[:3])
print("\nTransformed vector y:")
print(y)
print("\nGround truth solution x:")
print(x_ground_truth)


Transformed vector y:
[-9.09648416e+01 -8.33052161e+00  7.10542736e-15  3.55271368e-15]

Ground truth solution x:
[-2.00000000e+00  8.00000000e+00 -1.58882186e-14]


In [23]:
x_ls = np.linalg.lstsq(A, b, rcond=None)[0]
x_ls

array([-2.00000000e+00,  8.00000000e+00, -1.72919885e-14])

In [24]:
A @ x_ls  

array([14., 32., 50., 68.])

In [30]:
# Back substitution function
def back_substitution(R, y):
    n = len(y)
    x = np.zeros_like(y)
    for i in range(n-1, -1, -1):
        x[i] = y[i]
        for j in range(i+1, n):
            x[i] -= R[i, j] * x[j]
        x[i] /= R[i, i]
        print(f"Step {n-i}: x[{i}] = {x[i]}")
    return x

# Perform back substitution
x_back_sub = back_substitution(R[:3, :3], y[:3])
print("\nSolution x from back substitution:")
print(x_back_sub)

Step 1: x[2] = -1.588821858078257e-14
Step 2: x[1] = 8.00000000000002
Step 3: x[0] = -2.000000000000001

Solution x from back substitution:
[-2.00000000e+00  8.00000000e+00 -1.58882186e-14]


In [29]:
x = [-2.,  8. , 0]
A @ x


array([14., 32., 50., 68.])

In [20]:
A @ x_ls

array([14., 32., 50., 68.])

In [31]:
import numpy as np

# Function to generate a large full rank matrix
def generate_full_rank_matrix(rows, cols):
    while True:
        A = np.random.rand(rows, cols)
        if np.linalg.matrix_rank(A) == min(rows, cols):
            return A

# Generate a large full rank matrix A with dimensions 100x100
A_large = generate_full_rank_matrix(100, 100)
print("Generated matrix A_large:")
print(A_large)
print("\nRank of A_large:", np.linalg.matrix_rank(A_large))

Generated matrix A_large:
[[0.39277139 0.56833825 0.74518497 ... 0.97199616 0.31833171 0.07698237]
 [0.95906024 0.6043671  0.33689803 ... 0.65326847 0.74779684 0.69989679]
 [0.37817717 0.32307346 0.05911778 ... 0.81209578 0.1510176  0.14338931]
 ...
 [0.12015686 0.6309248  0.68655598 ... 0.64126297 0.51579686 0.13964899]
 [0.59267698 0.53240495 0.20219841 ... 0.3777771  0.77141595 0.50394243]
 [0.62972001 0.93340826 0.43937479 ... 0.98968616 0.79582035 0.68881195]]

Rank of A_large: 100


In [36]:
# Formulate Ax = b
A = A_large
# Generate corresponding b
b = np.random.rand(100)
# Generate corresponding Generate b corresponding b

# QR decomposition
Q, R = qr(A)

# Least squares solution
x_ls = np.linalg.lstsq(A, b, rcond=None)[0]


In [37]:
x_ls

array([ 0.02376694,  0.13772428, -0.23288546,  0.44934196, -0.01189586,
        0.55872784, -0.00592033, -0.61771007,  0.345865  , -0.16994033,
       -0.55529745,  0.05344196,  0.39643376,  0.53120753, -0.44156878,
        0.78994622,  0.58287553,  0.40072416, -0.56067571, -0.14930712,
       -0.26004964, -0.04297613, -0.31128426,  0.09984143,  0.26747429,
        0.01999254, -0.67766302, -0.12193662,  0.17071146,  0.13432589,
       -0.24318214, -0.49924819,  0.04310104, -0.48477273,  0.57469251,
        0.31910187, -0.0039459 , -0.23619324,  0.01731311,  0.19256007,
        0.03320502, -0.18929815, -0.19777682, -0.71872023, -0.33487047,
       -0.53272292, -0.69488945, -0.02319232,  0.14896215,  0.04948139,
       -0.63806234, -0.11039234,  0.28304965,  0.36299366,  0.03239088,
       -0.06172152, -0.42683294,  0.56573753, -0.33015597, -0.4962316 ,
       -0.87281936,  0.5779338 ,  0.53873383, -0.30673663,  0.34313283,
       -0.05662596,  0.43983733, -0.08724854,  0.14683028,  0.36

In [38]:
A

array([[0.39277139, 0.56833825, 0.74518497, ..., 0.97199616, 0.31833171,
        0.07698237],
       [0.95906024, 0.6043671 , 0.33689803, ..., 0.65326847, 0.74779684,
        0.69989679],
       [0.37817717, 0.32307346, 0.05911778, ..., 0.81209578, 0.1510176 ,
        0.14338931],
       ...,
       [0.12015686, 0.6309248 , 0.68655598, ..., 0.64126297, 0.51579686,
        0.13964899],
       [0.59267698, 0.53240495, 0.20219841, ..., 0.3777771 , 0.77141595,
        0.50394243],
       [0.62972001, 0.93340826, 0.43937479, ..., 0.98968616, 0.79582035,
        0.68881195]])

In [13]:
import numpy as np
from scipy.linalg import qr
M_DIM = 20
N_DIM = 10
a_matrix = [
  0.501677878500818, 0.5247012616710286, 0.298667344485938, 0.9322197592305858, 0.11745546054180955, 0.39930171253120716, 0.41230288623522715, 0.6058507383101019, 0.8072800500915411, 0.5604554739559301,
  0.5370373813938146, 0.7903942229521561, 0.08216670952235139, 0.7623272970464692, 0.05200387615191515, 0.15448748107218602, 0.32461444971706355, 0.752981951513194, 0.9834351098973194, 0.6762362604180372,
  0.5837994309123647, 0.6526847771405143, 0.4097422681077334, 0.48373917984556536, 0.0060695586827295145, 0.8617157541605, 0.24537497130024222, 0.6052963479461797, 0.299739207181138, 0.757890119691541,
  0.38968850040102343, 0.24230764547886863, 0.9168347575718511, 0.4235354563525442, 0.08689518749342962, 0.428705765988463, 0.6147772261564387, 0.9957814471973021, 0.5645976878873578, 0.23575068547501865,
  0.5363546553805804, 0.3036770682747426, 0.8792671167424453, 0.9710865747018259, 0.4434544403291758, 0.2106785701481353, 0.29153571566693115, 0.9282665735289257, 0.8206445980802755, 0.546198018539901,
  0.9481705915599232, 0.49747076770872, 0.25841206626285507, 0.6056262356379917, 0.5450632119772107, 0.30995264324693883, 0.1385117030462476, 0.9027716443187739, 0.08807362949234676, 0.9294652150338286,
  0.21981979109765626, 0.3392021492819459, 0.7961672273445339, 0.4454513398106902, 0.18563628204484772, 0.7729422203077319, 0.9367167683230162, 0.7926705746737054, 0.7781701286234575, 0.443705503652737,
  0.5434528302860749, 0.08375222926250236, 0.8223185415727753, 0.4955179129160775, 0.5192266708501538, 0.06749481650652067, 0.29305403067215574, 0.08364338851691622, 0.8846352530468458, 0.18898265166148476,
  0.6335388338473593, 0.11252428984672869, 0.6245097816720162, 0.8361933809553463, 0.44808248823098684, 0.6387800768970031, 0.8133002796800319, 0.776150037992171, 0.06220569055743963, 0.21737923586630115,
  0.2369728509439455, 0.679407230854394, 0.8093198926615255, 0.027172918028223192, 0.9255297154005543, 0.7558137719692413, 0.10366300694367847, 0.8746716502062198, 0.01584903739660437, 0.9083739748664194,
  0.36424921224437457, 0.16503778745876363, 0.693377390108795, 0.8224807890476129, 0.4607795998497808, 0.4662081397096034, 0.498679820889132, 0.8086376049640857, 0.2979278865317705, 0.6051322970404264,
  0.45656861627514556, 0.768068579013806, 0.11349648765479481, 0.11419639199011022, 0.9269329892656067, 0.8748203849097973, 0.9943510784574083, 0.5521463885131558, 0.20042295848423752, 0.9874922553513686,
  0.8883940474859748, 0.1974000837731973, 0.1602028482770953, 0.6771390507647046, 0.9728336618160538, 0.7329937549165493, 0.026899596122746394, 0.6653275739477409, 0.6288756266355067, 0.7295911925163864,
  0.7175715544489747, 0.1739318905450713, 0.05152476235608894, 0.24123941774053526, 0.5923076732601564, 0.42573046513035995, 0.8244788453208612, 0.8681296592230402, 0.9971507025593631, 0.8841331445189974,
  0.7277933546152744, 0.2733291461456403, 0.6477674765357697, 0.7304886330256406, 0.7119314017173244, 0.980025627927981, 0.7968165041217113, 0.7266329605880925, 0.03973113222986968, 0.05258773002110739,
  0.36751708945756056, 0.6042256483899476, 0.2414604254605851, 0.8897263137163277, 0.06043070657464944, 0.4906407388224938, 0.6079620554032535, 0.6985507303878778, 0.35245363961158727, 0.05563131431605206,
  0.7484477089103644, 0.22672376215668677, 0.7619335897580374, 0.6939804168429914, 0.30949909664667297, 0.8524911100316845, 0.2990790668921993, 0.2269888863757028, 0.6180282585633979, 0.9443748482117298,
  0.42543758355234695, 0.9178583125788091, 0.790005606967984, 0.23505553317739547, 0.2753986261793694, 0.23308784415151929, 0.6016241768539099, 0.5422817569054452, 0.4168969224327076, 0.9990803320735234,
  0.07288119028000484, 0.7340634790897558, 0.5546907024984212, 0.7022234227663862, 0.4853665281958527, 0.45257403014583597, 0.43233335795652217, 0.5519377865980033, 0.06823583058302651, 0.5788076490567865,
  0.3947765240911596, 0.9696761928034087, 0.7064550303347691, 0.6756401256097787, 0.5908663255630459, 0.517602623107613, 0.03422999815191263, 0.29872791891006323, 0.5849089768260868, 0.11871312076137153]
b_vec= [
  0.9639378469970425, 0.12948654746186405, 0.2701152009230662, 0.7637343838572136, 0.2848735011930813, 0.5563063563577612, 0.44371581058399057, 0.6027296145154326, 0.4785693789211989, 0.48148835694270264,
  0.48896450271893066, 0.9077409481872526, 0.5355577688464482, 0.18978592074871437, 0.6492901296402414, 0.8144905782479713, 0.6904705841353598, 0.9012819212313005, 0.08105506559841802, 0.12282527810259658,
]
# Reshape the input data to form matrix A and vector b
A = np.array(a_matrix).reshape(M_DIM, N_DIM)
b = np.array(b_vec)

# QR decomposition
Q, R = qr(A)

# Calculate y
y = Q.T @ b

print("Matrix R:")
print(R)
print("\nTransformed vector y:")
print(y)

Matrix R:
[[-2.49660377 -1.71374565 -1.99709373 -2.50154571 -1.89987138 -2.22090024
  -1.81687409 -2.73462387 -2.02486485 -2.45918916]
 [ 0.         -1.69794525 -0.70589849 -0.47375114 -0.37086249 -0.61046681
  -0.51855645 -0.7397241  -0.33958783 -0.87009157]
 [ 0.          0.          1.68048571  0.52811199  0.25395533  0.43098079
   0.4913601   0.53251227  0.33646057 -0.01214592]
 [ 0.          0.          0.          1.2546422  -0.39305445 -0.08814588
   0.08974593  0.24804308  0.332478   -0.54156121]
 [ 0.          0.          0.          0.          1.24452031  0.40659217
   0.10935681  0.17195232 -0.33163598  0.14130596]
 [ 0.          0.          0.          0.          0.          1.15050862
   0.60555167  0.21846078 -0.37221674  0.06200663]
 [ 0.          0.          0.          0.          0.          0.
  -1.34799061 -0.50821316 -0.36653525 -0.10354498]
 [ 0.          0.          0.          0.          0.          0.
   0.          1.08440655 -0.0378504   0.34724644]
 [ 0. 

In [10]:
def householder(A):
    m, n = A.shape
    R = np.copy(A)
    Q = np.eye(m)
    V = []
    for k in range(n):
        v = np.copy(R[k:,k])
        print(v.shape)
        v = np.reshape(v, (m-k, 1))
        v[0] += np.sign(v[0]) * np.linalg.norm(v)
        v /= np.linalg.norm(v)
        R[k:,k:] = R[k:,k:] - 2 * v @ v.T @ R[k:,k:]
        V.append(v)
    return R, V

In [14]:
R_hh, V = householder(A)

(20,)
(19,)
(18,)
(17,)
(16,)
(15,)
(14,)
(13,)
(12,)
(11,)


In [19]:
V

[array([[0.77490133],
        [0.13879649],
        [0.15088207],
        [0.1007144 ],
        [0.13862004],
        [0.24505325],
        [0.05681209],
        [0.14045456],
        [0.16373715],
        [0.06124527],
        [0.09413965],
        [0.11799946],
        [0.22960409],
        [0.18545528],
        [0.18809708],
        [0.09498423],
        [0.19343517],
        [0.1099537 ],
        [0.01883603],
        [0.10202939]]),
 array([[ 0.78401793],
        [ 0.08144178],
        [-0.0182632 ],
        [-0.0363399 ],
        [-0.07902949],
        [ 0.06576295],
        [-0.12093307],
        [-0.1353875 ],
        [ 0.18873253],
        [-0.04015196],
        [ 0.16045631],
        [-0.17497269],
        [-0.13588677],
        [-0.10141992],
        [ 0.12388865],
        [-0.12471639],
        [ 0.22544613],
        [ 0.25527424],
        [ 0.25350638]]),
 array([[-0.72300497],
        [ 0.25812027],
        [ 0.20002159],
        [-0.17679312],
        [ 0.24536723],
    

In [7]:
A.shape

(20, 10)

In [18]:
np.linalg.norm(R - R_hh)

3.4070554223191436e-15

In [20]:
A_small = [
  0.9125242884150524, 0.2618526048108707, 0.2522309100703436, 0.8227398627336125, 0.7566466389375209, 0.6164772665377012, 0.13463747123633585, 0.7354967634292587, 0.5915891614306871, 0.9578767525311169,
  0.11452831110610484, 0.5738647650751649, 0.08071819723851947, 0.04222830679534306, 0.6545516085569919, 0.6916324277590843, 0.5424758501357161, 0.1813777041902388, 0.9984198302177123, 0.021801973969179156,
  0.4636075442669806, 0.8259032534574547, 0.8221278474023749, 0.28922053856469154, 0.04582664640863787, 0.22125015960213557, 0.9660188422246867, 0.9770186878286297, 0.538190736610081, 0.8202618030853698,
  0.19309957782918408, 0.27098613189921605, 0.4080521892167669, 0.5656025557127724, 0.8340960960968165, 0.7906774426803732, 0.26293706175339815, 0.7991134497015253, 0.10046406941399999, 0.019449039876698326,
  0.007921818726771557, 0.1941769437030385, 0.71062783555477, 0.43263914937961023, 0.5693477087275669, 0.3204242298581954, 0.5596015134361886, 0.7675117828614614, 0.729019399346412, 0.8928129816035499,
  0.3852692170624098, 0.7225416266857754, 0.6302801575937815, 0.8367077392029664, 0.08425986431659793, 0.3894308373392179, 0.23737484289130673, 0.7205959105695015, 0.4824166658743615, 0.24337984434811588,
  0.05240818617556864, 0.7903124392165799, 0.46338182013337825, 0.9137599393284074, 0.1847908295813302, 0.27917226496834147, 0.6493254498005768, 0.4218543107870626, 0.48265117662731283, 0.19039607475207654,
  0.16575713726478036, 0.10089446130498658, 0.4901456961538695, 0.8963051899789372, 0.8697652014806521, 0.0834682077474952, 0.36653643754911014, 0.471106986105138, 0.9611894018126785, 0.8544199980547883,
  0.8813112351888436, 0.5913865256973991, 0.9767552525408504, 0.4091625943032051, 0.14211700098085545, 0.2736814942161243, 0.43631212084839, 0.4398953381186531, 0.9263980030130923, 0.8882554965580646,
  0.961901654791125, 0.0808232807661785, 0.11011279469619395, 0.10618325866542822, 0.08197180003610838, 0.07652692289735141, 0.7918299352164084, 0.023151840703882764, 0.5157937950495667, 0.7824130264629826,
  0.09591940900923723, 0.37506181974781017, 0.5777334351927227, 0.2474217062129761, 0.3144610310483029, 0.6414251819496957, 0.8538203235258695, 0.11184236758846056, 0.295504476313584, 0.8172498473756301,
  0.8622385446226385, 0.0807257704724712, 0.0895771145043931, 0.29306066482631266, 0.15840851210413343, 0.5564131185841314, 0.22323389971038576, 0.5532341909629258, 0.45956131120340926, 0.6838654325888245,
]

In [21]:
R_small, V_small = householder(A_small)

AttributeError: 'list' object has no attribute 'shape'

In [22]:
A_small = np.array(A_small).reshape(20, 6)

In [23]:
R_small, V_small = householder(A_small)

(20,)
(19,)
(18,)
(17,)
(16,)
(15,)


In [ ]:
V_small 

[array([[0.8230551 ],
        [0.03180493],
        [0.01906777],
        [0.23585315],
        [0.01082547],
        [0.04561522],
        [0.06211268],
        [0.16786908],
        [0.17221365],
        [0.01990441],
        [0.0123802 ],
        [0.15338783],
        [0.11578537],
        [0.22705834],
        [0.03357179],
        [0.22722659],
        [0.18705116],
        [0.13647591],
        [0.06980597],
        [0.03742028]]),
 array([[ 8.19787021e-01],
        [ 5.76728833e-04],
        [-1.50093724e-01],
        [ 6.22961872e-02],
        [ 5.47694653e-02],
        [ 2.09688467e-01],
        [ 2.41977724e-02],
        [ 1.65857855e-01],
        [ 1.09084221e-01],
        [ 2.40017031e-01],
        [ 3.04461686e-02],
        [ 2.04503539e-01],
        [ 1.17302802e-01],
        [ 6.36301221e-02],
        [-1.25813475e-01],
        [-1.17195709e-01],
        [-1.30934862e-02],
        [ 2.10266230e-01],
        [ 1.49881681e-01]]),
 array([[ 0.85189193],
        [ 0.094451  

In [28]:
R_small

array([[-2.57165444e+00, -1.48167025e+00, -1.68753222e+00,
        -1.85932988e+00, -1.85519981e+00, -1.48587581e+00],
       [-5.55111512e-17, -1.94164395e+00, -1.17179514e+00,
        -8.87775749e-01, -5.66601328e-01, -1.06166032e+00],
       [-2.77555756e-17,  6.50521303e-19, -1.34774394e+00,
        -1.00267775e+00, -7.37124507e-01, -6.87293838e-01],
       [-5.55111512e-16, -2.22044605e-16, -2.77555756e-17,
        -1.64073388e+00, -7.21639782e-01, -6.25780056e-01],
       [-2.77555756e-17,  0.00000000e+00, -1.11022302e-16,
         2.77555756e-17,  1.27664878e+00,  5.25253914e-01],
       [-1.11022302e-16,  2.77555756e-17, -2.77555756e-17,
         0.00000000e+00,  0.00000000e+00, -1.00710125e+00],
       [-1.66533454e-16,  1.11022302e-16,  0.00000000e+00,
        -5.55111512e-17,  6.93889390e-18,  0.00000000e+00],
       [-3.33066907e-16, -1.38777878e-17, -2.77555756e-17,
        -5.55111512e-17,  0.00000000e+00,  5.55111512e-17],
       [-3.33066907e-16,  1.11022302e-16,  5.551

In [29]:
def is_full_rank(matrix):
    return np.linalg.matrix_rank(matrix) == min(matrix.shape)

# Check if matrix A is full rank
A = np.array([[1, 2], [3, 4], [5, 6]])
is_A_full_rank = is_full_rank(A)
print(f"Matrix A is full rank: {is_A_full_rank}")

# Check if matrix A_small is full rank
is_A_small_full_rank = is_full_rank(A_small)
print(f"Matrix A_small is full rank: {is_A_small_full_rank}")

Matrix A is full rank: True
Matrix A_small is full rank: True


In [ ]:
# Read matrix Q from a text file
Q = np.loadtxt("Q_matrix.txt")
# Read matrix R from a text file
R = np.loadtxt('R_matrix.txt')

print("Matrix Q:")
print(Q)
print("\nMatrix R:")
print(R) 

FileNotFoundError: [Errno 2] No such file or directory