In [2]:
import numpy as np
from scipy.linalg import qr

# Example matrix A and vector b
A = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([7, 8, 9])

# QR decomposition
Q, R = qr(A)

# Least squares solution
x_ls = np.linalg.lstsq(A, b, rcond=None)[0]

print("Matrix A:")
print(A)
print("\nVector b:")
print(b)
print("\nMatrix Q:")
print(Q)
print("\nMatrix R:")
print(R)
print("\nLeast squares solution x:")
print(x_ls)

Matrix A:
[[1 2]
 [3 4]
 [5 6]]

Vector b:
[7 8 9]

Matrix Q:
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]

Matrix R:
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]

Least squares solution x:
[-6.   6.5]


In [21]:
import numpy as np
from scipy.linalg import qr

# More complicated matrix A and vector b
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10], [10, 11, 13]])
b = np.array([14, 32, 50, 68])

# QR decomposition
Q, R = qr(A)

# Least squares solution
x_ls = np.linalg.lstsq(A, b, rcond=None)[0]

print("Matrix A:")
print(A)
print("\nVector b:")
print(b)
print("\nMatrix Q:")
print(Q)
print("\nMatrix R:")
print(R)
print("\nLeast squares solution x:")
print(x_ls)

y = Q.T @ b
x_ground_truth = np.linalg.solve(R[:3, :3], y[:3])
print("\nTransformed vector y:")
print(y)
print("\nGround truth solution x:")
print(x_ground_truth)

Matrix A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]
 [10 11 13]]

Vector b:
[14 32 50 68]

Matrix Q:
[[-0.07761505 -0.83305216 -0.2236068  -0.5       ]
 [-0.31046021 -0.45123659  0.67082039  0.5       ]
 [-0.54330537 -0.06942101 -0.67082039  0.5       ]
 [-0.77615053  0.31239456  0.2236068  -0.5       ]]

Matrix R:
[[-12.88409873 -14.59162988 -17.61861693]
 [  0.          -1.0413152   -1.83965686]
 [  0.           0.          -0.4472136 ]
 [  0.           0.           0.        ]]

Least squares solution x:
[-2.00000000e+00  8.00000000e+00 -1.72919885e-14]

Transformed vector y:
[-9.09648416e+01 -8.33052161e+00  7.10542736e-15  3.55271368e-15]

Ground truth solution x:
[-2.00000000e+00  8.00000000e+00 -1.58882186e-14]


In [22]:

y = Q.T @ b
x_ground_truth = np.linalg.solve(R[:3, :3], y[:3])
print("\nTransformed vector y:")
print(y)
print("\nGround truth solution x:")
print(x_ground_truth)


Transformed vector y:
[-9.09648416e+01 -8.33052161e+00  7.10542736e-15  3.55271368e-15]

Ground truth solution x:
[-2.00000000e+00  8.00000000e+00 -1.58882186e-14]


In [23]:
x_ls = np.linalg.lstsq(A, b, rcond=None)[0]
x_ls

array([-2.00000000e+00,  8.00000000e+00, -1.72919885e-14])

In [24]:
A @ x_ls  

array([14., 32., 50., 68.])

In [30]:
# Back substitution function
def back_substitution(R, y):
    n = len(y)
    x = np.zeros_like(y)
    for i in range(n-1, -1, -1):
        x[i] = y[i]
        for j in range(i+1, n):
            x[i] -= R[i, j] * x[j]
        x[i] /= R[i, i]
        print(f"Step {n-i}: x[{i}] = {x[i]}")
    return x

# Perform back substitution
x_back_sub = back_substitution(R[:3, :3], y[:3])
print("\nSolution x from back substitution:")
print(x_back_sub)

Step 1: x[2] = -1.588821858078257e-14
Step 2: x[1] = 8.00000000000002
Step 3: x[0] = -2.000000000000001

Solution x from back substitution:
[-2.00000000e+00  8.00000000e+00 -1.58882186e-14]


In [29]:
x = [-2.,  8. , 0]
A @ x


array([14., 32., 50., 68.])

In [20]:
A @ x_ls

array([14., 32., 50., 68.])

In [31]:
import numpy as np

# Function to generate a large full rank matrix
def generate_full_rank_matrix(rows, cols):
    while True:
        A = np.random.rand(rows, cols)
        if np.linalg.matrix_rank(A) == min(rows, cols):
            return A

# Generate a large full rank matrix A with dimensions 100x100
A_large = generate_full_rank_matrix(100, 100)
print("Generated matrix A_large:")
print(A_large)
print("\nRank of A_large:", np.linalg.matrix_rank(A_large))

Generated matrix A_large:
[[0.39277139 0.56833825 0.74518497 ... 0.97199616 0.31833171 0.07698237]
 [0.95906024 0.6043671  0.33689803 ... 0.65326847 0.74779684 0.69989679]
 [0.37817717 0.32307346 0.05911778 ... 0.81209578 0.1510176  0.14338931]
 ...
 [0.12015686 0.6309248  0.68655598 ... 0.64126297 0.51579686 0.13964899]
 [0.59267698 0.53240495 0.20219841 ... 0.3777771  0.77141595 0.50394243]
 [0.62972001 0.93340826 0.43937479 ... 0.98968616 0.79582035 0.68881195]]

Rank of A_large: 100


In [36]:
# Formulate Ax = b
A = A_large
# Generate corresponding b
b = np.random.rand(100)
# Generate corresponding Generate b corresponding b

# QR decomposition
Q, R = qr(A)

# Least squares solution
x_ls = np.linalg.lstsq(A, b, rcond=None)[0]


In [37]:
x_ls

array([ 0.02376694,  0.13772428, -0.23288546,  0.44934196, -0.01189586,
        0.55872784, -0.00592033, -0.61771007,  0.345865  , -0.16994033,
       -0.55529745,  0.05344196,  0.39643376,  0.53120753, -0.44156878,
        0.78994622,  0.58287553,  0.40072416, -0.56067571, -0.14930712,
       -0.26004964, -0.04297613, -0.31128426,  0.09984143,  0.26747429,
        0.01999254, -0.67766302, -0.12193662,  0.17071146,  0.13432589,
       -0.24318214, -0.49924819,  0.04310104, -0.48477273,  0.57469251,
        0.31910187, -0.0039459 , -0.23619324,  0.01731311,  0.19256007,
        0.03320502, -0.18929815, -0.19777682, -0.71872023, -0.33487047,
       -0.53272292, -0.69488945, -0.02319232,  0.14896215,  0.04948139,
       -0.63806234, -0.11039234,  0.28304965,  0.36299366,  0.03239088,
       -0.06172152, -0.42683294,  0.56573753, -0.33015597, -0.4962316 ,
       -0.87281936,  0.5779338 ,  0.53873383, -0.30673663,  0.34313283,
       -0.05662596,  0.43983733, -0.08724854,  0.14683028,  0.36

In [38]:
A

array([[0.39277139, 0.56833825, 0.74518497, ..., 0.97199616, 0.31833171,
        0.07698237],
       [0.95906024, 0.6043671 , 0.33689803, ..., 0.65326847, 0.74779684,
        0.69989679],
       [0.37817717, 0.32307346, 0.05911778, ..., 0.81209578, 0.1510176 ,
        0.14338931],
       ...,
       [0.12015686, 0.6309248 , 0.68655598, ..., 0.64126297, 0.51579686,
        0.13964899],
       [0.59267698, 0.53240495, 0.20219841, ..., 0.3777771 , 0.77141595,
        0.50394243],
       [0.62972001, 0.93340826, 0.43937479, ..., 0.98968616, 0.79582035,
        0.68881195]])