In [2]:
import numpy as np
from scipy.linalg import qr

# Example matrix A and vector b
A = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([7, 8, 9])

# QR decomposition
Q, R = qr(A)

# Least squares solution
x_ls = np.linalg.lstsq(A, b, rcond=None)[0]

print("Matrix A:")
print(A)
print("\nVector b:")
print(b)
print("\nMatrix Q:")
print(Q)
print("\nMatrix R:")
print(R)
print("\nLeast squares solution x:")
print(x_ls)

Matrix A:
[[1 2]
 [3 4]
 [5 6]]

Vector b:
[7 8 9]

Matrix Q:
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]

Matrix R:
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]

Least squares solution x:
[-6.   6.5]


In [ ]:
import numpy as np
from scipy.linalg import qr

# More complicated matrix A and vector b
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10], [10, 11, 13]])
b = np.array([14, 32, 50, 68])

# QR decomposition
Q, R = qr(A)

# Least squares solution
x_ls = np.linalg.lstsq(A, b, rcond=None)[0]

print("Matrix A:")
print(A)
print("\nVector b:")
print(b)
print("\nMatrix Q:")
print(Q)
print("\nMatrix R:")
print(R)
print("\nLeast squares solution x:")
print(x_ls)

y = Q.T @ b
x_ground_truth = np.linalg.solve(R[:3, :3], y[:3])
print("\nTransformed vector y:")
print(y)
print("\nGround truth solution x:")
print(x_ground_truth)

Matrix A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Vector b:
[14 32 50 68]

Matrix Q:
[[-0.07761505 -0.83305216  0.5472782  -0.0220583 ]
 [-0.31046021 -0.45123659 -0.71326299  0.43732815]
 [-0.54330537 -0.06942101 -0.21530863 -0.80848141]
 [-0.77615053  0.31239456  0.38129342  0.39321156]]

Matrix R:
[[-1.28840987e+01 -1.45916299e+01 -1.62991610e+01]
 [ 0.00000000e+00 -1.04131520e+00 -2.08263040e+00]
 [ 0.00000000e+00  0.00000000e+00 -4.51848010e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

Least squares solution x:
[1. 2. 3.]

Transformed vector y:
[-9.09648416e+01 -8.33052161e+00  0.00000000e+00  7.10542736e-15]

Ground truth solution x:
[-2.  8. -0.]


In [9]:

y = Q.T @ b
x_ground_truth = np.linalg.solve(R[:3, :3], y[:3])
print("\nTransformed vector y:")
print(y)
print("\nGround truth solution x:")
print(x_ground_truth)


Transformed vector y:
[-9.09648416e+01 -8.33052161e+00  0.00000000e+00  7.10542736e-15]

Ground truth solution x:
[-2.  8. -0.]


In [14]:
x_ls = np.linalg.lstsq(A, b, rcond=None)[0]
x_ls

array([1., 2., 3.])

In [17]:
A @ x_ls  

array([14., 32., 50., 68.])

In [18]:
# Back substitution function
def back_substitution(R, y):
    n = len(y)
    x = np.zeros_like(y)
    for i in range(n-1, -1, -1):
        x[i] = y[i]
        for j in range(i+1, n):
            x[i] -= R[i, j] * x[j]
        x[i] /= R[i, i]
        print(f"Step {n-i}: x[{i}] = {x[i]}")
    return x

# Perform back substitution
x_back_sub = back_substitution(R[:3, :3], y[:3])
print("\nSolution x from back substitution:")
print(x_back_sub)

Step 1: x[2] = -0.0
Step 2: x[1] = 7.999999999999991
Step 3: x[0] = -1.9999999999999907

Solution x from back substitution:
[-2.  8. -0.]


In [19]:
x = [-2.,  8. , -0.]
A @ x


array([14., 32., 50., 68.])

In [20]:
A @ x_ls

array([14., 32., 50., 68.])